### ISSUE TITLE
Should we get rid of 'wiggles'?

### ISSUE THREAD

**Issue by nickmalleson** [Urban-Analytics/dust#18]
They kind of made sense in the original version when movement was always left to right, but were largely a fudge. Now that there is better collision detection, should we redesign the collision avoidance routine?

**Comment by patricia-ternes** [comment]
@nickmalleson, I didn't understand what you meant. Can you explain your idea better?

**Comment by nickmalleson** [comment]
It's OK we discussed it and the wiggles can stay for now!
