### ISSUE TITLE
Document the difference between `total_time` and `step_id`

### ISSUE THREAD

**Issue by ksuchak1990** [Urban-Analytics/dust#68]
In stationsim_gcs, two different variables are used in the model when considering time: `total_time` and `step_id`.

It appears that `total_time` is used to model "continuous time", allowing us to handle cases where an agent's trajectory needs to be altered to avoid collisions, whereas `step_id` simply counts the number of times the model `step` method is called. If this is the case, it is perhaps somewhat misleading for the time at which an agent should activate to be referred to as `steps_activate` - should this be `time_activate` instead?

**Comment by ksuchak1990** [comment]
I may be overthinking this a little bit, but @nickmalleson and @patricia-ternes it would be good to get your input on this if possible?

**Comment by ksuchak1990** [comment]
Similarly, when `Agent.deactivate()` is run (in the case where `model.do_history == True`), we calculate `steps_taken = self.model.total_time - self.step_start`; the latter term is simply `self.model.total_time` at the time when the agent was activated. Would it be more appropriate to call this `time_taken`?

**Comment by nickmalleson** [comment]
Good questions @ksuchak1990 . I think that you're right, but it's definitely worth checking with @patricia-ternes . She may not be seeing these alerts - could you try her on email or slack?

**Comment by patricia-ternes** [comment]
For the first case, there is no difference because total_time and step_id have the same value outside the while statement. The steps_activate is a integer number.
But, having the same value, perhaps using time_activate is better because it is easier to understand.

For the second case, steps_taken is called inside the while statement, so, the result can be a continuous time. Definitely, it is more appropriate here to use time_taken.

**Comment by ksuchak1990** [comment]
Thanks for getting back to me. Are you refering to the version on the master branch or a different version? (I'm guessing you're refering to a different version as there aren't any `while` loops relating to `Agent.activate()` and `Agent.deactivate()` on master).

I'm currently looking at the version on master, in which `step_id` is always incremented in integer values; it appears that `Model.total_time` may be incremented by non-integer values in cases when the minimum collision time is less than 1. This leads me to believe `step_id` simply denotes the integer number of time-steps taken whereas `total_time` denotes the amount of time that has passed inside the model (a continuous variable) which are different values. 

In this version, `Agent.step_activate` is drawn from an exponential distribution (i.e. it is a continuous variable), and is compared against `time_taken`; it would, therefore, make sense for it be named `Agent.time_activate`. 

Similarly, I would argue that the calculation of `steps_taken` upon deactivation should be consistent with regards to notation and variable type: either we calculate `steps_taken = self.model.step_id - self.step_activate` where `self.step_activate` should be the model `step_id` recorded when the agent is activated, or we calculate `time_taken = self.model.time_taken - self.time_activate` where  `self.time_activate` should be the model `time_taken` recorded when the agent is activated.
